{{- if .Values.postgres.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: main
  POSTGRES_USER: default
  POSTGRES_PASSWORD: secret
{{- end }}