name: main
run-name: ${{ github.actor }} - Testing and publishing

on:
  push:
    paths-ignore:
    - '*.md'
    - '**/*.md'

jobs: 
  prepare:
    name: Prepare variables
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.prepare.outputs.version }}
      commit: ${{ steps.prepare.outputs.commit }}
      branch: ${{ steps.prepare.outputs.branch }}
      tag: ${{ steps.prepare.outputs.tag }} 
    steps:
    - name: Prepare variables
      id: prepare
      shell: bash
      run: |
        BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr '\' '-')
        COMMIT_SHA_SHORT=$(echo ${GITHUB_SHA} | cut -c1-7)
        VERSION=$(echo ${BRANCH}-${COMMIT_SHA_SHORT})
        TAG=$(echo ${GITHUB_REF#refs/*/})

        echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "commit=${COMMIT_SHA_SHORT}" >> $GITHUB_OUTPUT
        echo "branch=${BRANCH}" >> $GITHUB_OUTPUT

        echo version: $VERSION
        echo commit: $COMMIT_SHA_SHORT
        echo branch: $BRANCH
        echo tag: $TAG 
 
  update:
    needs:
      - prepare
    name: Update CRM Version
    runs-on: ubuntu-latest 

    steps:
    - name: Check out code
      uses: actions/checkout@v2
 
    - name: Update Image Tag Values
      uses: mikefarah/yq@master
      with:
        cmd: yq -i  '.image.tag = "${{ needs.prepare.outputs.tag }}"' "./backend/crm/values-dev.yaml"
    
    - name: Commit the changes made
      run: | 
        git config --global user.name 'github-workflow'
        git config --global user.email 'github-workflow@gmail.com'
        git commit -am "updating image tag"
        git push